#!/usr/bin/env bash
#
# Rebuilds the package docs after a commit.
#
# Move to .git/hooks/post-commit
#
set -e

if [ $(git rev-parse --abbrev-ref HEAD) == "master" ]; then

    git checkout gh-pages &&
	echo "Checked out github pages branch"

    git merge master -X theirs -m "merged master" &&
	echo "Merged master branch"

    Rscript build-docs.R && git commit -am 'updated docs' && git push &&
	echo "Uploaded documentation"

    git checkout master &&
	echo "Switched back to master"

fi
